{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: 'str' object is not callable", "trace": "self = <test_login.TestLogin object at 0x000000ECC9528C50>\n\n    def test_login(self):\n        try:\n            driver =self.driver\n            driver.get(utils.URL)\n            log = login(driver)\n            log.usernamebox(utils.username)\n            log.passwordbox(utils.password)\n            log.logintab()\n>           x = driver.title()\nE           TypeError: 'str' object is not callable\n\ntests\\test_login.py:21: TypeError"}, "start": 1564386799706, "stop": 1564386806162, "uuid": "cc964157-c7c9-4236-9fe4-9efaf57b5362", "historyId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "qhpunm7lp55"}, {"name": "thread", "value": "7380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}