{"uuid": "e52ce1af-736c-4f70-a15a-4bb3f2bb5974", "children": ["f78558da-8cf9-4f92-8a78-65a595010b7f", "11d92ccb-6da9-410a-b0ba-ad20aa808caa"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\conftest.py\", line 6, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../PytestFrame1/drivers/chromedriver.exe\")\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1564387724884, "stop": 1564387724884}], "start": 1564387724884, "stop": 1564387725150}