{"uuid": "707e8080-1237-46e7-a367-fa2de9656c8f", "children": ["495cbd5e-63b6-4b13-8073-9f5d7aa4239b", "27fd36b2-f679-4389-850c-d227b100553a"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\conftest.py\", line 6, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../PytestFrame1/drivers/chromedriver.exe\")\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\ganesh.lakariya\\PycharmProjects\\PytestFrame1\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1564387660597, "stop": 1564387660597}], "start": 1564387660597, "stop": 1564387660956}